"""The seams between services and the outside world. Services depend on these, never on adapters."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Protocol

from review_loop.types.agents import AgentError, PhaseOutput, PhaseRequest
from review_loop.types.discussion import Discussion
from review_loop.types.pull_request import PullRef, PullRequest
from review_loop.types.result import Result


@dataclass(frozen=True)
class CompletedRun:
    argv: list[str]
    exit_code: int
    stdout: str
    stderr: str
    timed_out: bool = False


class ProcessRunner(Protocol):
    def run(self, argv: list[str], cwd: str, env: dict[str, str], timeout_seconds: int, stdin: str = "",
            stdout_path: str | None = None) -> CompletedRun: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


class GitClient(Protocol):
    def merge_base(self, repo_path: str, one: str, two: str) -> str: ...

    def fetch(self, repo_path: str, remote: str, refs: list[str]) -> None: ...

    def worktree_exists(self, path: str) -> bool: ...

    def worktree_add(self, repo_path: str, path: str, branch: str, start_point: str) -> None: ...

    def is_clean(self, path: str) -> bool: ...

    def reset_hard(self, path: str, sha: str) -> None: ...

    # Scoped to the worktree at `path`; the repository's shared config, read by every checkout, is never written.
    def set_worktree_push_url(self, path: str, remote: str, url: str) -> None: ...

    def changed_files(self, repo_path: str, base: str, head: str) -> list[str]: ...

    def diff(self, repo_path: str, base: str, head: str) -> str: ...

    def log_between(self, repo_path: str, base: str, head: str) -> list[str]: ...

    def head_sha(self, path: str) -> str: ...

    def file_hash(self, path: str, sha: str, file: str) -> str: ...

    def paths_differing_from(self, path: str, base: str, pathspecs: list[str]) -> list[str]: ...
    def working_changed_files(self, path: str) -> list[str]: ...

    def stage_all_and_tree_hash(self, path: str) -> str: ...

    # The patch from base to tree, written to destination as git produces it: binary-safe and free of the user's diff
    # settings, so `git apply` on base reproduces the tree.
    def write_patch(self, path: str, base: str, tree: str, destination: str) -> None: ...

    # The tree `stage_all_and_tree_hash` would write, computed in a scratch index so the worktree's own index is untouched.
    def working_tree_hash(self, path: str) -> str: ...

    def commit(self, path: str, message: str) -> str: ...

    def commit_info(self, path: str, sha: str) -> tuple[str, str]: ...

    def commit_tree(self, path: str, sha: str) -> str: ...

    def current_branch(self, path: str) -> str: ...

    def push_guarded(self, path: str, url: str, sha: str, remote_branch: str, expected_remote_sha: str) -> Result[str, str]: ...

    # Where the remote branch points right now, from git itself; "" when the branch does not exist.
    def remote_branch_head(self, path: str, url: str, branch: str) -> str: ...


class GitHubGateway(Protocol):
    def fetch_pull(self, ref: PullRef) -> PullRequest: ...

    def fetch_discussion(self, ref: PullRef) -> Discussion: ...

    def post_comment(self, ref: PullRef, body: str) -> dict: ...

    def post_review(self, ref: PullRef, body: str, commit_sha: str, comments: list[dict]) -> dict: ...

    def reply_to_comment(self, ref: PullRef, comment_id: int, body: str) -> dict: ...

    def edit_comment(self, ref: PullRef, comment_id: int, body: str) -> dict: ...

    def resolve_thread(self, thread_id: str) -> dict: ...

    def find_post_by_marker(self, ref: PullRef, marker: str) -> dict | None: ...


class AgentAdapter(Protocol):
    def run(self, request: PhaseRequest) -> Result[PhaseOutput, AgentError]: ...


class Notifier(Protocol):
    def notify(self, title: str, message: str) -> None: ...
