from review_loop.config.settings import DEFAULT_FORBIDDEN_TRAILERS
from review_loop.engine.trailers import strip_forbidden_trailers


def test_the_default_policy_strips_ordinary_provenance_wording_too():
    message = ("fix: x\n\nBody.\n\nGenerated by Claude Code\nAssisted by ChatGPT\n🤖 Generated with [Claude Code](https://claude.com)\n"
               "Co-Authored-By: Codex <codex@openai.com>\nSigned-off-by: Claude <noreply@anthropic.com>\n")

    cleaned = strip_forbidden_trailers(message, DEFAULT_FORBIDDEN_TRAILERS)

    assert cleaned == "fix: x\n\nBody.\n"


def test_a_line_that_merely_mentions_a_model_as_a_provider_survives():
    message = "feat(ai): route Claude requests through the new provider adapter\n\nBody.\n"

    assert strip_forbidden_trailers(message, DEFAULT_FORBIDDEN_TRAILERS) == message
