"""Trusted operator configuration, loaded from a TOML file outside any reviewed repository."""

from __future__ import annotations

import difflib
import tomllib
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from review_loop.types.agents import AGENT_PROFILES
from review_loop.types.run import AgentChoice

DEFAULT_TIMEOUTS_MINUTES = {"review": 40, "assess": 20, "fix": 60, "verify": 60, "align": 15, "arbitrate": 15}
DEFAULT_FORBIDDEN_TRAILERS = ["Co-Authored-By", "Generated with", "Generated by", "Assisted by", "Assisted-by", "🤖",
                              "Signed-off-by: Claude", "Signed-off-by: Codex", "Signed-off-by: ChatGPT"]


class ConfigError(Exception):
    """A configuration file is missing something or has the wrong shape; the message says what and where."""


@dataclass(frozen=True)
class WorkspaceConfig:
    prepare: list[list[str]]
    prepare_when_paths_match: dict[str, list[list[str]]] = field(default_factory=dict)
    sanitize_env: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class VerificationConfig:
    required: list[list[str]]
    unavailable_exit_codes: list[int] = field(default_factory=list)
    format: list[list[str]] = field(default_factory=list)


@dataclass(frozen=True)
class ReviewConfig:
    max_review_passes: int = 7
    max_fix_attempts: int = 2
    max_alignment_exchanges: int = 1
    reviewer: str = "codex"
    author: str = "claude"
    reviewer_model: str = AGENT_PROFILES["codex"].default_model
    reviewer_effort: str = AGENT_PROFILES["codex"].default_effort
    author_model: str = AGENT_PROFILES["claude"].default_model
    author_effort: str = AGENT_PROFILES["claude"].default_effort
    timeouts_minutes: dict[str, int] = field(default_factory=lambda: dict(DEFAULT_TIMEOUTS_MINUTES))

    def agents(self) -> dict[str, AgentChoice]:
        """The reviewer and author as a run records them at start."""
        return {"reviewer": AgentChoice(self.reviewer, self.reviewer_model, self.reviewer_effort),
                "author": AgentChoice(self.author, self.author_model, self.author_effort)}


@dataclass(frozen=True)
class PublicationConfig:
    post_reviews: bool = True
    post_author_responses: bool = True
    push_verified_fixes: bool = True
    mirror_inbox_in_pr_comment: bool = True
    forbid_commit_trailers: list[str] = field(default_factory=lambda: list(DEFAULT_FORBIDDEN_TRAILERS))


@dataclass(frozen=True)
class RepositoryConfig:
    name: str
    remote: str
    local_path: Path
    worktree_root: Path
    workspace: WorkspaceConfig
    verification: VerificationConfig
    instruction_files: list[str] = field(default_factory=list)
    allowed_pr_authors: list[str] = field(default_factory=list)
    trusted_logins: list[str] = field(default_factory=list)
    review: ReviewConfig = field(default_factory=ReviewConfig)
    publication: PublicationConfig = field(default_factory=PublicationConfig)


@dataclass(frozen=True)
class Settings:
    state_dir: Path
    repositories: dict[str, RepositoryConfig]
    source: Path

    def agents(self) -> list[str]:
        """Every agent some repository uses as reviewer or author."""
        return sorted({name for repo in self.repositories.values() for name in (repo.review.reviewer, repo.review.author)})


def load_settings(path: Path) -> Settings:
    try:
        raw = tomllib.loads(path.read_text())
    except FileNotFoundError:
        raise ConfigError(f"config file not found: {path}; register a repository with `review-loop repo add <path>`") from None
    except tomllib.TOMLDecodeError as error:
        raise ConfigError(f"{path}: not valid TOML: {error}") from None
    reader = _Reader(path)
    state_dir = Path(reader.string(raw, "state_dir"))
    tables = reader.table(raw, "repositories")
    repositories = {name: _repository(reader, name, reader.table(tables, name, "repositories")) for name in tables}
    reader.reject_unknown(raw, ("state_dir", "repositories"))
    if not repositories:
        raise ConfigError(f"{path}: no [repositories.<name>] table; register one with `review-loop repo add`")
    return Settings(state_dir=state_dir, repositories=repositories, source=path)


def _repository(reader: _Reader, name: str, table: dict[str, Any]) -> RepositoryConfig:
    prefix = f"repositories.{name}"
    values = {
        "remote": reader.string(table, "remote", prefix),
        "local_path": Path(reader.string(table, "local_path", prefix)),
        "worktree_root": Path(reader.string(table, "worktree_root", prefix)),
        "instruction_files": reader.string_list(table, "instruction_files", prefix, default=[]),
        "allowed_pr_authors": reader.string_list(table, "allowed_pr_authors", prefix, default=[]),
        "trusted_logins": reader.string_list(table, "trusted_logins", prefix, default=[]),
        "workspace": _workspace(reader, reader.table(table, "workspace", prefix), f"{prefix}.workspace"),
        "verification": _verification(reader, reader.table(table, "verification", prefix), f"{prefix}.verification"),
        "review": _review(reader, reader.table(table, "review", prefix, default={}), f"{prefix}.review"),
        "publication": _publication(reader, reader.table(table, "publication", prefix, default={}), f"{prefix}.publication"),
    }
    reader.reject_unknown(table, values, prefix)
    return RepositoryConfig(name=name, **values)


def _workspace(reader: _Reader, workspace: dict[str, Any], prefix: str) -> WorkspaceConfig:
    by_path = reader.table(workspace, "prepare_when_paths_match", prefix, default={})
    values = {
        "prepare": reader.commands(workspace, "prepare", prefix),
        "prepare_when_paths_match": {pattern: reader.commands(by_path, pattern, f"{prefix}.prepare_when_paths_match")
                                     for pattern in by_path},
        "sanitize_env": reader.string_list(workspace, "sanitize_env", prefix, default=[]),
    }
    reader.reject_unknown(workspace, values, prefix)
    return WorkspaceConfig(**values)


def _verification(reader: _Reader, verification: dict[str, Any], prefix: str) -> VerificationConfig:
    values = {
        "required": reader.commands(verification, "required", prefix),
        "unavailable_exit_codes": reader.integer_list(verification, "unavailable_exit_codes", prefix, default=[]),
        "format": reader.commands(verification, "format", prefix, default=[]),
    }
    reader.reject_unknown(verification, values, prefix)
    return VerificationConfig(**values)


def _review(reader: _Reader, review: dict[str, Any], prefix: str) -> ReviewConfig:
    timeouts = reader.table(review, "timeouts_minutes", prefix, default={})
    timeouts_prefix = f"{prefix}.timeouts_minutes"
    minutes = {phase: reader.integer(timeouts, phase, timeouts_prefix, default=default)
               for phase, default in DEFAULT_TIMEOUTS_MINUTES.items()}
    reader.reject_unknown(timeouts, minutes, timeouts_prefix)
    values = {
        **_agents(reader, review, prefix),
        **{key: reader.integer(review, key, prefix, default=getattr(ReviewConfig, key))
           for key in ("max_review_passes", "max_fix_attempts", "max_alignment_exchanges")},
        "timeouts_minutes": minutes,
    }
    reader.reject_unknown(review, values, prefix)
    return ReviewConfig(**values)


def _agents(reader: _Reader, review: dict[str, Any], prefix: str) -> dict[str, str]:
    """Model and effort default to the chosen agent's own, so switching agents never inherits another CLI's model."""
    values = {}
    for role in ("reviewer", "author"):
        name = reader.string(review, role, prefix, default=getattr(ReviewConfig, role))
        if name not in AGENT_PROFILES:
            raise reader._fail(role, prefix, f"must be one of {', '.join(sorted(AGENT_PROFILES))}")
        profile = AGENT_PROFILES[name]
        values.update({role: name,
                       f"{role}_model": reader.string(review, f"{role}_model", prefix, default=profile.default_model),
                       f"{role}_effort": reader.string(review, f"{role}_effort", prefix, default=profile.default_effort)})
    return values


def _publication(reader: _Reader, publication: dict[str, Any], prefix: str) -> PublicationConfig:
    values = {
        **{key: reader.boolean(publication, key, prefix, default=getattr(PublicationConfig, key))
           for key in ("post_reviews", "post_author_responses", "push_verified_fixes", "mirror_inbox_in_pr_comment")},
        "forbid_commit_trailers": reader.string_list(publication, "forbid_commit_trailers", prefix, default=DEFAULT_FORBIDDEN_TRAILERS),
    }
    reader.reject_unknown(publication, values, prefix)
    return PublicationConfig(**values)


class _Reader:
    """Typed access to a parsed TOML tree; every failure names the dotted key and the file."""

    def __init__(self, path: Path):
        self.path = path

    def _fail(self, key: str, prefix: str, problem: str) -> ConfigError:
        dotted = f"{prefix}.{key}" if prefix else key
        return ConfigError(f"{self.path}: {dotted} {problem}")

    def string(self, table: dict[str, Any], key: str, prefix: str = "", default: str | None = None) -> str:
        value = table.get(key, default)
        if value is None:
            raise self._fail(key, prefix, "is required")
        if not isinstance(value, str):
            raise self._fail(key, prefix, "must be a string")
        return value

    def integer(self, table: dict[str, Any], key: str, prefix: str, default: int | None = None) -> int:
        value = table.get(key, default)
        if value is None:
            raise self._fail(key, prefix, "is required")
        if not _is_integer(value):
            raise self._fail(key, prefix, "must be an integer")
        return value

    def boolean(self, table: dict[str, Any], key: str, prefix: str, default: bool | None = None) -> bool:
        value = table.get(key, default)
        if value is None:
            raise self._fail(key, prefix, "is required")
        if not isinstance(value, bool):
            raise self._fail(key, prefix, "must be true or false")
        return value

    def table(self, table: dict[str, Any], key: str, prefix: str = "", default: dict[str, Any] | None = None) -> dict[str, Any]:
        value = table.get(key, default)
        if value is None:
            raise self._fail(key, prefix, "is required")
        if not isinstance(value, dict):
            raise self._fail(key, prefix, "must be a table")
        return value

    def reject_unknown(self, table: dict[str, Any], known: Iterable[str], prefix: str = "") -> None:
        """A key nothing reads is almost always a typo, and ignoring it would silently keep the default."""
        known = sorted(known)
        for key in table:
            if key not in known:
                close = difflib.get_close_matches(key, known, n=1)
                hint = f"did you mean {close[0]}?" if close else f"known keys: {', '.join(known)}"
                raise self._fail(key, prefix, f"is not a known key ({hint})")

    def string_list(self, table: dict[str, Any], key: str, prefix: str, default: list[str] | None = None) -> list[str]:
        value = table.get(key, default)
        if value is None:
            raise self._fail(key, prefix, "is required")
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            raise self._fail(key, prefix, "must be an array of strings")
        return list(value)

    def integer_list(self, table: dict[str, Any], key: str, prefix: str, default: list[int] | None = None) -> list[int]:
        value = table.get(key, default)
        if value is None:
            raise self._fail(key, prefix, "is required")
        if not isinstance(value, list) or not all(_is_integer(item) for item in value):
            raise self._fail(key, prefix, "must be an array of integers")
        return list(value)

    def commands(self, table: dict[str, Any], key: str, prefix: str, default: list[list[str]] | None = None) -> list[list[str]]:
        value = table.get(key, default)
        if value is None:
            raise self._fail(key, prefix, "is required")
        if not isinstance(value, list) or not all(_is_argv(command) for command in value):
            raise self._fail(key, prefix, "must be an array of commands, each an array of argument strings (never a shell string)")
        return [list(command) for command in value]


def _is_argv(command: Any) -> bool:
    return isinstance(command, list) and len(command) > 0 and all(isinstance(argument, str) for argument in command)


def _is_integer(value: Any) -> bool:
    # bool subclasses int, so `true` would otherwise pass as 1.
    return isinstance(value, int) and not isinstance(value, bool)
