"""Trusted operator configuration, loaded from a TOML file outside any reviewed repository."""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from review_loop.types.agents import AGENT_PROFILES

DEFAULT_TIMEOUTS_MINUTES = {"review": 40, "assess": 20, "fix": 60, "verify": 60, "align": 15, "arbitrate": 15}
DEFAULT_FORBIDDEN_TRAILERS = ["Co-Authored-By", "Generated with", "Generated by", "Assisted by", "Assisted-by", "🤖",
                              "Signed-off-by: Claude", "Signed-off-by: Codex", "Signed-off-by: ChatGPT"]


class ConfigError(Exception):
    """A configuration file is missing something or has the wrong shape; the message says what and where."""


@dataclass(frozen=True)
class WorkspaceConfig:
    prepare: list[list[str]]
    prepare_when_paths_match: dict[str, list[list[str]]] = field(default_factory=dict)
    sanitize_env: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class VerificationConfig:
    required: list[list[str]]
    unavailable_exit_codes: list[int] = field(default_factory=list)
    format: list[list[str]] = field(default_factory=list)


@dataclass(frozen=True)
class ReviewConfig:
    max_review_passes: int = 7
    max_fix_attempts: int = 2
    max_alignment_exchanges: int = 1
    reviewer: str = "codex"
    author: str = "claude"
    reviewer_model: str = "gpt-6-astra"
    reviewer_effort: str = "ultra"
    author_model: str = "claude-fable-5-1"
    author_effort: str = "high"
    timeouts_minutes: dict[str, int] = field(default_factory=lambda: dict(DEFAULT_TIMEOUTS_MINUTES))


@dataclass(frozen=True)
class PublicationConfig:
    post_reviews: bool = True
    post_author_responses: bool = True
    push_verified_fixes: bool = True
    mirror_inbox_in_pr_comment: bool = True
    forbid_commit_trailers: list[str] = field(default_factory=lambda: list(DEFAULT_FORBIDDEN_TRAILERS))


@dataclass(frozen=True)
class RepositoryConfig:
    name: str
    remote: str
    local_path: Path
    worktree_root: Path
    workspace: WorkspaceConfig
    verification: VerificationConfig
    instruction_files: list[str] = field(default_factory=list)
    allowed_pr_authors: list[str] = field(default_factory=list)
    trusted_logins: list[str] = field(default_factory=list)
    review: ReviewConfig = field(default_factory=ReviewConfig)
    publication: PublicationConfig = field(default_factory=PublicationConfig)


@dataclass(frozen=True)
class Settings:
    state_dir: Path
    repositories: dict[str, RepositoryConfig]
    source: Path

    def agents(self) -> list[str]:
        """Every agent some repository uses as reviewer or author."""
        return sorted({name for repo in self.repositories.values() for name in (repo.review.reviewer, repo.review.author)})


def load_settings(path: Path) -> Settings:
    try:
        raw = tomllib.loads(path.read_text())
    except FileNotFoundError:
        raise ConfigError(f"config file not found: {path}") from None
    except tomllib.TOMLDecodeError as error:
        raise ConfigError(f"{path}: not valid TOML: {error}") from None
    reader = _Reader(path)
    state_dir = Path(reader.string(raw, "state_dir"))
    repositories = {
        name: _repository(reader, name, table)
        for name, table in reader.table(raw, "repositories").items()
    }
    if not repositories:
        raise ConfigError(f"{path}: no [repositories.<name>] table; register one with `review-loop repo add`")
    return Settings(state_dir=state_dir, repositories=repositories, source=path)


def _repository(reader: _Reader, name: str, table: dict[str, Any]) -> RepositoryConfig:
    prefix = f"repositories.{name}"
    workspace = reader.table(table, "workspace", prefix)
    verification = reader.table(table, "verification", prefix)
    review = table.get("review", {})
    publication = table.get("publication", {})
    return RepositoryConfig(
        name=name,
        remote=reader.string(table, "remote", prefix),
        local_path=Path(reader.string(table, "local_path", prefix)),
        worktree_root=Path(reader.string(table, "worktree_root", prefix)),
        instruction_files=reader.string_list(table, "instruction_files", prefix, default=[]),
        allowed_pr_authors=reader.string_list(table, "allowed_pr_authors", prefix, default=[]),
        trusted_logins=reader.string_list(table, "trusted_logins", prefix, default=[]),
        workspace=WorkspaceConfig(
            prepare=reader.commands(workspace, "prepare", f"{prefix}.workspace"),
            prepare_when_paths_match={
                pattern: reader.commands(workspace["prepare_when_paths_match"], pattern, f"{prefix}.workspace.prepare_when_paths_match")
                for pattern in workspace.get("prepare_when_paths_match", {})
            },
            sanitize_env=reader.string_list(workspace, "sanitize_env", f"{prefix}.workspace", default=[]),
        ),
        verification=VerificationConfig(
            required=reader.commands(verification, "required", f"{prefix}.verification"),
            unavailable_exit_codes=list(verification.get("unavailable_exit_codes", [])),
            format=reader.commands(verification, "format", f"{prefix}.verification", default=[]),
        ),
        review=ReviewConfig(
            **{**_agent_defaults(reader, review, f"{prefix}.review"),
               **{key: value for key, value in review.items() if key != "timeouts_minutes"}},
            timeouts_minutes={**DEFAULT_TIMEOUTS_MINUTES, **review.get("timeouts_minutes", {})},
        ),
        publication=PublicationConfig(**publication),
    )


def _agent_defaults(reader: _Reader, review: dict[str, Any], prefix: str) -> dict[str, str]:
    """Model and effort default to the chosen agent's own, so switching agents never inherits another CLI's model."""
    defaults = {}
    for role in ("reviewer", "author"):
        name = review.get(role, getattr(ReviewConfig, role))
        if name not in AGENT_PROFILES:
            raise reader._fail(role, prefix, f"must be one of {', '.join(sorted(AGENT_PROFILES))}")
        profile = AGENT_PROFILES[name]
        defaults.update({role: name, f"{role}_model": profile.default_model, f"{role}_effort": profile.default_effort})
    return defaults


class _Reader:
    """Typed access to a parsed TOML tree; every failure names the dotted key and the file."""

    def __init__(self, path: Path):
        self.path = path

    def _fail(self, key: str, prefix: str, problem: str) -> ConfigError:
        dotted = f"{prefix}.{key}" if prefix else key
        return ConfigError(f"{self.path}: {dotted} {problem}")

    def string(self, table: dict[str, Any], key: str, prefix: str = "") -> str:
        value = table.get(key)
        if value is None:
            raise self._fail(key, prefix, "is required")
        if not isinstance(value, str):
            raise self._fail(key, prefix, "must be a string")
        return value

    def table(self, table: dict[str, Any], key: str, prefix: str = "") -> dict[str, Any]:
        value = table.get(key)
        if value is None:
            raise self._fail(key, prefix, "is required")
        if not isinstance(value, dict):
            raise self._fail(key, prefix, "must be a table")
        return value

    def string_list(self, table: dict[str, Any], key: str, prefix: str, default: list[str] | None = None) -> list[str]:
        value = table.get(key, default)
        if value is None:
            raise self._fail(key, prefix, "is required")
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            raise self._fail(key, prefix, "must be an array of strings")
        return list(value)

    def commands(self, table: dict[str, Any], key: str, prefix: str, default: list[list[str]] | None = None) -> list[list[str]]:
        value = table.get(key, default)
        if value is None:
            raise self._fail(key, prefix, "is required")
        if not isinstance(value, list) or not all(_is_argv(command) for command in value):
            raise self._fail(key, prefix, "must be an array of commands, each an array of argument strings (never a shell string)")
        return [list(command) for command in value]


def _is_argv(command: Any) -> bool:
    return isinstance(command, list) and len(command) > 0 and all(isinstance(argument, str) for argument in command)
